services:
  - type: web
    name: bloomberg-copper-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    branch: main
    autoDeploy: true